# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('hotel', models.CharField(choices=[('NP', 'Nivel principiante'), ('NA', 'Nivel aficionado'), ('NS', 'Nivel semiprofesional'), ('NPL', 'Nivel profesional')], default='NP', max_length=3)),
                ('date_registry', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
