# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriber',
            old_name='hotel',
            new_name='nivel',
        ),
    ]
