# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_auto_20170304_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriber',
            new_name='Inscritos',
        ),
    ]
