# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_inscritos_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='nivel',
            field=models.CharField(choices=[('NP', 'Nivel principiante'), ('NS', 'Nivel semiprofesional'), ('NPL', 'Nivel profesional')], default='NP', max_length=3),
        ),
    ]
