# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_auto_20170315_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='nivel',
            field=models.CharField(choices=[('NV', 'Nivel novato'), ('IN', 'Nivel intermedio'), ('AV', 'Nivel avanzado')], default='NP', max_length=3),
        ),
    ]
